/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_greenstone_mg_MGSearchWrapper */

#ifndef _Included_org_greenstone_mg_MGSearchWrapper
#define _Included_org_greenstone_mg_MGSearchWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    initCSide
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_greenstone_mg_MGSearchWrapper_initCSide
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    unloadIndexData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_greenstone_mg_MGSearchWrapper_unloadIndexData
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setCase
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setCase
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setStem
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setStem
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setMaxDocs
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setMaxDocs
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setReturnTerms
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setReturnTerms
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setIndex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setMatchMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setMatchMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    getQueryParams
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_greenstone_mg_MGSearchWrapper_getQueryParams
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    setMaxNumeric
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_setMaxNumeric
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_greenstone_mg_MGSearchWrapper
 * Method:    runQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGSearchWrapper_runQuery
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
