/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_greenstone_mg_MGWrapper */

#ifndef _Included_org_greenstone_mg_MGWrapper
#define _Included_org_greenstone_mg_MGWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    initCSide
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_greenstone_mg_MGWrapper_initCSide
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    getDocument
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_greenstone_mg_MGWrapper_getDocument
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    unloadIndexData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_greenstone_mg_MGWrapper_unloadIndexData
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setCase
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setCase
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setStem
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setStem
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setMaxDocs
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setMaxDocs
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setReturnTerms
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setReturnTerms
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setIndex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setMatchMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setMatchMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    getQueryParams
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_greenstone_mg_MGWrapper_getQueryParams
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    setMaxNumeric
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_setMaxNumeric
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_greenstone_mg_MGWrapper
 * Method:    runQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGWrapper_runQuery
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
