/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_greenstone_mg_MGRetrieveWrapper */

#ifndef _Included_org_greenstone_mg_MGRetrieveWrapper
#define _Included_org_greenstone_mg_MGRetrieveWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_greenstone_mg_MGRetrieveWrapper
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGRetrieveWrapper_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_greenstone_mg_MGRetrieveWrapper
 * Method:    initCSide
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_greenstone_mg_MGRetrieveWrapper_initCSide
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGRetrieveWrapper
 * Method:    getDocument
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_greenstone_mg_MGRetrieveWrapper_getDocument
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     org_greenstone_mg_MGRetrieveWrapper
 * Method:    unloadIndexData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_greenstone_mg_MGRetrieveWrapper_unloadIndexData
  (JNIEnv *, jobject);

/*
 * Class:     org_greenstone_mg_MGRetrieveWrapper
 * Method:    setIndex
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_greenstone_mg_MGRetrieveWrapper_setIndex
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
